### ISSUE TITLE
"ReferenceError: document is not defined" when building a static website with Gridsome

### ISSUE THREAD

**Issue by mlquiros** [peremp/vue-light-gallery#12]
I'm using this component in my [Gridsome](https://gridsome.org) static site styled with [Tailwind](https://tailwindcss.com). While building the app (using `gridsome develop`) in development mode works, building the app for deployment (`gridsome build`) generates the following error:

```
ReferenceError: document is not defined
    at Object.336 (node_modules/vue-light-gallery/dist/vue-light-gallery.esm.js:228:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.371 (assets/js/page--src--pages--about-apcess-vue.f311ae3d.js:217:29)
    at __webpack_require__ (webpack/bootstrap:25:0)
```

I'm not doing anything out of the ordinary with the component--I'm using it as a locally-imported one. HTML looks like:

```html
<light-gallery :images="fullImages"
  :index="currentIndex"
  :disable-scroll="false"
  @close="currentIndex = null" />

<div class="flex flex-row flex-wrap">
  <div v-for="(thumbnailUrl, index) in thumbnailImageUrls"
    class="p-1 w-1/3 md:w-1/6"
    @click="currentIndex = index">
    <div class="relative w-full h-full pb-3/4">
      <g-image class="absolute w-full h-full object-cover" :src="thumbnailUrl"/>
    </div>
  </div>
</div>
```

JavaScript looks like:

```js
<script>
// ...
import timelineItems from "@/data/apcess_timeline.json"

export default {
  components: {
    LightGallery
  },
  // ...
}
</script>
```

Thoughts? This is what Line 228 is in `node_modules/vue-light-gallery/dist/vue-light-gallery.esm.js`

```js
var HEAD = document.head || document.getElementsByTagName('head')[0];
```

**Comment by mlquiros** [comment]
Well that didn't take long. The solution was to import the component locally in a different way as per the [Gridsome docs](https://gridsome.org/docs/assets-scripts/#without-ssr-support) on Vue components without server-side rendering support.

Building for both development and deployment now works in Gridsome with the following code:

```html
<client-only>
  <light-gallery :images="fullImages"
    :index="currentIndex"
    :disable-scroll="false"
    @close="currentIndex = null" />
</client-only>

<div class="flex flex-row flex-wrap">
  <div v-for="(thumbnailUrl, index) in thumbnailImageUrls"
    class="p-1 w-1/3 md:w-1/6"
    @click="currentIndex = index">
    <div class="relative w-full h-full pb-3/4">
      <g-image class="absolute w-full h-full object-cover" :src="thumbnailUrl"/>
    </div>
  </div>
</div>
```

```js
<script>
export default {
  components: {
    LightGallery: () =>
      import ("vue-light-gallery")
        .then(m => m.LightGallery)
        .catch()
  }
}
</script>
```
